[package]
name = "swarm"
version = "0.1.0"
authors = ["Thomas vanden Bighelaar <thomas@beardiegames.com>"]
edition = "2018"
description = "Optimized object pooling system for Rust"
readme = "README.md"
license = "MIT"
license-file="License.txt"

[dependencies]
